[workspace]
members = [
  "core"
]

[package]
name = "ovior"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ovior"
path = "src/main.rs"

[dependencies]
bytes = "1.4.0"
core = { path = "core" }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.8"
